[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc = "0.8.28"
via_ir = true
fs_permissions = [{ access = "read", path = "./config/networks.json"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
